name: Biome

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Resolve Biome version from package.json
        run: echo "BIOME_VERSION=$(node -p \"require('./package.json').devDependencies['@biomejs/biome']\")" >> $GITHUB_ENV

      - name: Run Biome check (via npx to ensure correct platform binary)
        run: npx -y @biomejs/biome@${{ env.BIOME_VERSION }} check .
